// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestScenarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testScenario() {
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1382, 754));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("email_create")).click();
    driver.findElement(By.id("email_create")).sendKeys("rafiulbari@gmail.com");
    driver.findElement(By.id("email_create")).click();
    driver.findElement(By.id("email_create")).sendKeys("rafiulbarichowdhury2222@gmail.com");
    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    driver.findElement(By.cssSelector(".radio-inline:nth-child(3) > .top")).click();
    driver.findElement(By.id("customer_firstname")).click();
    driver.findElement(By.id("customer_firstname")).sendKeys("Rafiul");
    driver.findElement(By.id("customer_lastname")).sendKeys("Chowdhury");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("KaDwycZu2767U9w");
    driver.findElement(By.id("days")).click();
    {
      WebElement dropdown = driver.findElement(By.id("days"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:1\\s+']")).click();
    }
    driver.findElement(By.id("months")).click();
    {
      WebElement dropdown = driver.findElement(By.id("months"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:January\\s']")).click();
    }
    driver.findElement(By.id("years")).click();
    {
      WebElement dropdown = driver.findElement(By.id("years"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:2006\\s+']")).click();
    }
    driver.findElement(By.id("years")).click();
    {
      WebElement dropdown = driver.findElement(By.id("years"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:1971\\s+']")).click();
    }
    driver.findElement(By.id("address1")).click();
    driver.findElement(By.id("address1")).sendKeys("Chittagong");
    driver.findElement(By.id("city")).sendKeys("Chattogram");
    driver.findElement(By.id("postcode")).sendKeys("4326");
    driver.findElement(By.id("id_state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Kansas']")).click();
    }
    driver.findElement(By.cssSelector(".columns-container")).click();
    driver.findElement(By.id("postcode")).sendKeys("00000");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("+8801911523151");
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    driver.findElement(By.linkText("Sign out")).click();
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("email_create")).click();
    driver.findElement(By.id("email_create")).click();
    driver.findElement(By.id("email_create")).sendKeys("rafiulbarichowdhury22222@gmail.com");
    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    driver.findElement(By.id("id_gender1")).click();
    driver.findElement(By.id("customer_firstname")).click();
    driver.findElement(By.id("customer_firstname")).sendKeys("Rafiul");
    driver.findElement(By.id("customer_lastname")).sendKeys("Chowdhury");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("KaDwycZu2767U9w");
    driver.findElement(By.id("days")).click();
    {
      WebElement dropdown = driver.findElement(By.id("days"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:2\\s+']")).click();
    }
    driver.findElement(By.id("months")).click();
    {
      WebElement dropdown = driver.findElement(By.id("months"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:April\\s']")).click();
    }
    driver.findElement(By.id("years")).click();
    {
      WebElement dropdown = driver.findElement(By.id("years"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:1927\\s+']")).click();
    }
    driver.findElement(By.id("address1")).click();
    driver.findElement(By.id("address1")).sendKeys("Chittagong");
    driver.findElement(By.id("city")).sendKeys("Chattogram");
    driver.findElement(By.id("postcode")).sendKeys("4326");
    driver.findElement(By.id("id_state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Arizona']")).click();
    }
    driver.findElement(By.cssSelector(".columns-container")).click();
    driver.findElement(By.id("postcode")).sendKeys("00000");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("+8801911523151");
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    driver.findElement(By.linkText("Sign out")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("rafiulbarichowdhury1111@gmail.com");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("KaDwycZu2767U9w");
    driver.findElement(By.cssSelector("#SubmitLogin > span")).click();
    driver.findElement(By.cssSelector(".sfHover:nth-child(1) > a")).click();
    driver.findElement(By.cssSelector(".ajax_add_to_cart_button > span")).click();
    driver.findElement(By.cssSelector(".cross")).click();
    driver.findElement(By.cssSelector(".sfHover > a")).click();
    driver.findElement(By.id("layered_id_attribute_group_14")).click();
    driver.findElement(By.cssSelector(".ajax_add_to_cart_button > span")).click();
    driver.findElement(By.cssSelector(".button-medium:nth-child(2) > span")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".button:nth-child(4) > span")).click();
    driver.findElement(By.id("cgv")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.linkText("Pay by check (order processing will be longer)")).click();
    driver.findElement(By.cssSelector("#cart_navigation span")).click();
    driver.findElement(By.linkText("Sign out")).click();
  }
}
